export const STAT_OPTIONS = [
  { value: "accuracyHead", label: "Headshot accuracy" },
  { value: "accuracyEnemySpotted", label: "Spotted accuracy" },
  { value: "sprayAccuracy", label: "Spray accuracy" },
  { value: "counterStrafingRatio", label: "Counter-strafing" },
  { value: "preaim", label: "Pre-aim" },
  { value: "reactionTimeMs", label: "Reaction time" },
  { value: "aimRating", label: "Aim rating" },
  { value: "utilityRating", label: "Utility rating" },
  { value: "positioningRating", label: "Positioning rating" },
  { value: "flashHitPerFlash", label: "Flash efficiency" },
  { value: "flashAvgDuration", label: "Flash duration" },
  { value: "flashLeadingToKill", label: "Flash assists" },
  { value: "heFoesDamageAvg", label: "HE damage" },
  { value: "utilityOnDeathAvg", label: "Unused utility on death" },
  { value: "ctOpeningSuccess", label: "CT opening duels" },
  { value: "tOpeningSuccess", label: "T opening duels" },
  { value: "tradeKillsSuccess", label: "Trade kills" },
  { value: "tradeDeathsSuccess", label: "Trade deaths" },
];
